#Library Imports
#Note: This code requires the 'pycryptodome' library. Make sure to install it using:
# pip install pycryptodome
from Crypto.Cipher import AES
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
from Crypto.Random import get_random_bytes
from Crypto.Util.Padding import pad, unpad

#Additional Imports
import base64

# AES Functions - Encryption and Decryption

#aes_encrypt - Encrypts plaintext using AES in CBC mode
def aes_encrypt(plaintext, key):
    #cipher is defined using AES with the provided key in CBC mode
    cipher = AES.new(key, AES.MODE_CBC)
    #ciphertext is generated by encrypting the padded plaintext 
    ciphertext = cipher.encrypt(pad(plaintext.encode(), AES.block_size))
    #returns the base64 encoded string of the IV concatenated with the ciphertext
    return base64.b64encode(cipher.iv + ciphertext).decode()

#aes_decrypt - Decrypts AES encrypted data using the provided key
def aes_decrypt(encrypted_data, key):
    #encrypted_data is base64 decoded to get the original byte data
    encrypted_data = base64.b64decode(encrypted_data)
    #IV is extracted from the beginning of the encrypted data
    iv = encrypted_data[:AES.block_size]
    #ciphertext is the remaining part of the encrypted data
    ciphertext = encrypted_data[AES.block_size:]
    #cipher is defined using AES with the provided key and extracted IV in CBC mode
    cipher = AES.new(key, AES.MODE_CBC, iv)
    #plaintext is obtained by decrypting the ciphertext and unpadding it
    plaintext = unpad(cipher.decrypt(ciphertext), AES.block_size)
    #returns the decoded plaintext string
    return plaintext.decode()

# RSA Functions - Encryption and Decryption

#rsa_encrypt - Encrypts plaintext using RSA public key
def rsa_encrypt(plaintext, public_key):
    #cipher is defined using PKCS1_OAEP with the provided public key
    cipher = PKCS1_OAEP.new(public_key)
    #ciphertext is generated by encrypting the plaintext
    ciphertext = cipher.encrypt(plaintext.encode())
    #returns the base64 encoded string of the ciphertext
    return base64.b64encode(ciphertext).decode()

#rsa_decrypt - Decrypts RSA encrypted data using private key
def rsa_decrypt(encrypted_data, private_key):
    #encrypted_data is base64 decoded to get the original byte data
    encrypted_data = base64.b64decode(encrypted_data)
    #cipher is defined using PKCS1_OAEP with the provided private key
    cipher = PKCS1_OAEP.new(private_key)
    #plaintext is obtained by decrypting the encrypted data
    plaintext = cipher.decrypt(encrypted_data)
    #returns the decoded plaintext string
    return plaintext.decode()

# Main function to demonstrate encryption and decryption
def main():
    print("=== Encryption/Decryption Educational Tool ===\n")
    
    # AES Demonstration
    print("--- AES (Symmetric Encryption) ---")
    # Generate a random 128-bit AES key
    aes_key = get_random_bytes(16)
    #Sample message for AES
    message = "Hello, this is a secret message!"
    
    #AES Encryption and Decryption
    print(f"Original message: {message}")
    #Run AES encryption function with given message and key
    encrypted_aes = aes_encrypt(message, aes_key)
    #Run AES decryption function with the encrypted data and key
    print(f"AES Encrypted: {encrypted_aes}")
    #Run AES decryption function with the encrypted data and key
    decrypted_aes = aes_decrypt(encrypted_aes, aes_key)
    #Print the decrypted AES message
    print(f"AES Decrypted: {decrypted_aes}")
    print(f"Match: {message == decrypted_aes}\n")
    
    # RSA Demonstration
    print("--- RSA (Asymmetric Encryption) ---")
    # Generate RSA key pair
    rsa_key = RSA.generate(2048)
    # Extract public key from the generated RSA key pair
    public_key = rsa_key.publickey()
    
    #Sample message for RSA
    short_message = "Secret data"  # RSA can only encrypt small messages
    print(f"Original message: {short_message}")
    #Runs RSA encryption function with given message and public key
    encrypted_rsa = rsa_encrypt(short_message, public_key)
    print(f"RSA Encrypted: {encrypted_rsa}")
   #Runs RSA decryption function with the encrypted data and private key
    decrypted_rsa = rsa_decrypt(encrypted_rsa, rsa_key)
    print(f"RSA Decrypted: {decrypted_rsa}")
    print(f"Match: {short_message == decrypted_rsa}\n")
    
    #User Interaction
    print("--- Try it yourself! ---")
    user_input = input("Enter a message to encrypt (or press Enter to skip): ")
    
    #If user provides input, demonstrate both AES and RSA encryption/decryption
    if user_input:
        # Demonstrate AES encryption and decryption with user input
        print("\n1. AES Encryption:")
        #Run AES encryption function with user input and generated key
        aes_result = aes_encrypt(user_input, aes_key)
        print(f"Encrypted: {aes_result}")
        print(f"Decrypted: {aes_decrypt(aes_result, aes_key)}")
        # Demonstrate RSA encryption and decryption with user input
        if len(user_input) < 200:  # RSA has size limitations
            print("\n2. RSA Encryption:")
            rsa_result = rsa_encrypt(user_input, public_key)
            print(f"Encrypted: {rsa_result}")
            print(f"Decrypted: {rsa_decrypt(rsa_result, rsa_key)}")
        else:
            print("\n2. RSA: Message too long for RSA encryption")


if __name__ == "__main__":
    main()
